version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "finn"

  liquibase:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: db-migrations
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/finn"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "pass"
      DATABASE_SCHEMA: "public"

  redis:
    image: redis
    ports:
      - "6379:6379"
