{
 "title": "Finn Advisor Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Основные цифры", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Пользователи",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT user_id) FROM categories LIMIT 50 "
    }
   ]
  },
  {
   "title": "Категории",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(category) FROM categories LIMIT 50 "
    }
   ]
  },
  {
   "title": "Операции",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM operations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Сообщения",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(type) FROM metrics WHERE type='new_message' LIMIT 50 "
    }
   ]
  },
  { "title": "Графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Количеcтво пользователей",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT SUM(COUNT(DISTINCT user_id)) OVER (ORDER BY date), date FROM categories GROUP BY date LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество операций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT date, SUM(COUNT(id)) OVER (ORDER BY date) FROM operations GROUP BY date;"
    }
   ]
  },
  {
   "title": "Количество добавленных категорий",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT SUM(COUNT(category)) OVER (ORDER BY date), date FROM categories GROUP BY date LIMIT 50 "
    }
   ]
  },
  {
   "title": "Топ самых популярных категорий",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT category, COUNT(user_id) AS cnt FROM categories GROUP BY category ORDER BY cnt DESC LIMIT 50"
    }
   ]
  },
  {
   "title": "Количество потраченных денег",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT SUM(sum) OVER (ORDER BY date), date FROM operations LIMIT 50 "
    }
   ]
  },
  { "title": "Статистика по сообщениям", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Количество сообщений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) OVER (ORDER BY time), time FROM metrics WHERE type='new_message' GROUP BY time, value;"
    }
   ]
  },
  {
   "title": "Топ сообщений по типам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) as total, labels\nFROM metrics WHERE type='new_message'\nGROUP BY labels\nORDER BY total DESC;"
    }
   ]
  }
 ]
}