name: Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd
      - name: composer install
        uses: docker://composer:2.4.4
        with:
          args: install
      - name: PHPUnit testing
        uses: docker://composer:2.4.4
        with:
          args: test
